baseurl = "/"
languageCode = "en-us"
title = "No Fancy Theme"
theme = "nofancy"

#if not set copyright, default copyright template will be applied
copyright = "Copyright (c) 2008 - 2014, Steve Francia; all rights reserved."

[params]
    highlight="Assign a syntax highlight style"

[author]
    name = "Steve Francia"
    github = "spf13"
    linkedin = "YOUR LINKEDIN ID"
    facebook = "YOUR FB ID"
    gaID = "YOUR Google Analytics Tracking ID"
    twitter = "YOUR TWITTER ID"
